################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal.c \
C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_adc.c \
C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_adc_ex.c \
C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_cortex.c \
C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_dma.c \
C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_gpio.c \
C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pwr.c \
C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pwr_ex.c \
C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rcc.c \
C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rcc_ex.c \
C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rtc.c \
C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rtc_ex.c \
C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_spi.c \
C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_spi_ex.c \
C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_uart.c \
C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_uart_ex.c 

OBJS += \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_adc.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_adc_ex.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_cortex.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_dma.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_gpio.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_pwr.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_pwr_ex.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rcc.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rcc_ex.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rtc.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rtc_ex.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_spi.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_spi_ex.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_uart.o \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_uart_ex.o 

C_DEPS += \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_adc.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_adc_ex.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_cortex.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_dma.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_gpio.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_pwr.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_pwr_ex.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rcc.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rcc_ex.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rtc.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rtc_ex.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_spi.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_spi_ex.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_uart.d \
./Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_uart_ex.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal.o: C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_STM32WBXX_NUCLEO -DSTM32WB55xx -DUSE_HAL_DRIVER -DCORE_CM4 -c -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/ -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../../Utilities/sequencer -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/menu -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../Core/Inc -I../../../STM32_WPAN/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_adc.o: C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_adc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_STM32WBXX_NUCLEO -DSTM32WB55xx -DUSE_HAL_DRIVER -DCORE_CM4 -c -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/ -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../../Utilities/sequencer -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/menu -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../Core/Inc -I../../../STM32_WPAN/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_adc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_adc_ex.o: C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_adc_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_STM32WBXX_NUCLEO -DSTM32WB55xx -DUSE_HAL_DRIVER -DCORE_CM4 -c -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/ -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../../Utilities/sequencer -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/menu -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../Core/Inc -I../../../STM32_WPAN/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_adc_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_cortex.o: C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_cortex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_STM32WBXX_NUCLEO -DSTM32WB55xx -DUSE_HAL_DRIVER -DCORE_CM4 -c -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/ -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../../Utilities/sequencer -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/menu -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../Core/Inc -I../../../STM32_WPAN/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_cortex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_dma.o: C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_dma.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_STM32WBXX_NUCLEO -DSTM32WB55xx -DUSE_HAL_DRIVER -DCORE_CM4 -c -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/ -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../../Utilities/sequencer -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/menu -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../Core/Inc -I../../../STM32_WPAN/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_dma.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_gpio.o: C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_gpio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_STM32WBXX_NUCLEO -DSTM32WB55xx -DUSE_HAL_DRIVER -DCORE_CM4 -c -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/ -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../../Utilities/sequencer -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/menu -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../Core/Inc -I../../../STM32_WPAN/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_gpio.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_pwr.o: C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pwr.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_STM32WBXX_NUCLEO -DSTM32WB55xx -DUSE_HAL_DRIVER -DCORE_CM4 -c -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/ -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../../Utilities/sequencer -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/menu -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../Core/Inc -I../../../STM32_WPAN/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_pwr.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_pwr_ex.o: C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pwr_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_STM32WBXX_NUCLEO -DSTM32WB55xx -DUSE_HAL_DRIVER -DCORE_CM4 -c -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/ -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../../Utilities/sequencer -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/menu -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../Core/Inc -I../../../STM32_WPAN/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_pwr_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rcc.o: C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rcc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_STM32WBXX_NUCLEO -DSTM32WB55xx -DUSE_HAL_DRIVER -DCORE_CM4 -c -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/ -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../../Utilities/sequencer -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/menu -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../Core/Inc -I../../../STM32_WPAN/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rcc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rcc_ex.o: C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rcc_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_STM32WBXX_NUCLEO -DSTM32WB55xx -DUSE_HAL_DRIVER -DCORE_CM4 -c -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/ -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../../Utilities/sequencer -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/menu -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../Core/Inc -I../../../STM32_WPAN/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rcc_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rtc.o: C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rtc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_STM32WBXX_NUCLEO -DSTM32WB55xx -DUSE_HAL_DRIVER -DCORE_CM4 -c -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/ -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../../Utilities/sequencer -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/menu -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../Core/Inc -I../../../STM32_WPAN/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rtc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rtc_ex.o: C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rtc_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_STM32WBXX_NUCLEO -DSTM32WB55xx -DUSE_HAL_DRIVER -DCORE_CM4 -c -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/ -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../../Utilities/sequencer -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/menu -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../Core/Inc -I../../../STM32_WPAN/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_rtc_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_spi.o: C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_spi.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_STM32WBXX_NUCLEO -DSTM32WB55xx -DUSE_HAL_DRIVER -DCORE_CM4 -c -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/ -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../../Utilities/sequencer -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/menu -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../Core/Inc -I../../../STM32_WPAN/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_spi.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_spi_ex.o: C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_spi_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_STM32WBXX_NUCLEO -DSTM32WB55xx -DUSE_HAL_DRIVER -DCORE_CM4 -c -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/ -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../../Utilities/sequencer -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/menu -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../Core/Inc -I../../../STM32_WPAN/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_spi_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_uart.o: C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_uart.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_STM32WBXX_NUCLEO -DSTM32WB55xx -DUSE_HAL_DRIVER -DCORE_CM4 -c -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/ -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../../Utilities/sequencer -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/menu -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../Core/Inc -I../../../STM32_WPAN/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_uart.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_uart_ex.o: C:/Users/nkgoe/Downloads/en.stm32cubewb_v1-4-0/STM32Cube_FW_WB_V1.4.0/Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_uart_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_STM32WBXX_NUCLEO -DSTM32WB55xx -DUSE_HAL_DRIVER -DCORE_CM4 -c -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/ -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../../Utilities/sequencer -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble/menu -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../Core/Inc -I../../../STM32_WPAN/App -Os -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WBxx_HAL_Driver/stm32wbxx_hal_uart_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

